name: weather
description: A new Flutter project about api calls
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  dio: ^5.2.1+1
  flutter_dotenv: ^5.1.0
  flutter_map: ^5.0.0
  latlong2: ^0.9.0
  geolocator: ^9.0.2
  flutter_native_splash: ^2.3.1
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  
  assets:
    - .env
    - assets/images/splash.png
    - assets/images/icon.png


flutter_icons:
  image_path: "assets/images/icon.png"
  android: true
  ios: true